DROP TABLE muscle CASCADE CONSTRAINTS;
DROP TABLE exercice CASCADE CONSTRAINTS;
DROP TABLE utilisateur CASCADE CONSTRAINTS ;

CREATE TABLE utilisateur (
    id_user NUMBER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    username VARCHAR2(50) UNIQUE,
    mdp VARCHAR2(50), 
    age NUMBER,
    gender VARCHAR2(50)
);

INSERT INTO utilisateur (first_name, last_name, username, mdp, age, gender) VALUES
('Alice', 'Dupont', 'alice123', 'passAlice', 25, 'Female');

INSERT INTO utilisateur (first_name, last_name, username, mdp, age, gender) VALUES
('Bob', 'Martin', 'bobmartin', 'passBob', 30, 'Male');

INSERT INTO utilisateur (first_name, last_name, username, mdp, age, gender) VALUES
('Claire', 'Durand', 'claireD', 'passClaire', 28, 'Female');

INSERT INTO utilisateur (first_name, last_name, username, mdp, age, gender) VALUES
('David', 'Lemoine', 'davidL', 'passDavid', 35, 'Male');

CREATE TABLE exercise (
    id_ex NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_ex DATE,
    username_ex VARCHAR2(50),
    muscle_cible VARCHAR2(50),
    exercise VARCHAR2(50),
    serie NUMBER,
    repetition NUMBER, 
    poids NUMBER(7,3),
    CONSTRAINT fk_username FOREIGN KEY (username_ex) REFERENCES utilisateur(username)
);

CREATE TABLE muscle (
    id_m NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    muscle_cible  VARCHAR2(50),
    nom_exercice VARCHAR2(50)
);

INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Chest','Bench Press');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Chest','Dumbbell Press');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Chest','Incline Bench Press');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Chest','Incline Dumbbell Press');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Chest','Decline Bench Press');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Chest','Chest Press Machine');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Chest','Close-Grip Bench Press');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Chest','Dumbbell Flyes');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Chest','Cable Crossover');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Chest','Push-ups');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Chest','Dumbbell Pullover');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Chest','Pec Deck Machine');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Chest','Chest Dips');

INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Back','Pull-ups');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Back','Lat Pulldown');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Back','Barbell Row');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Back','Dumbbell Row ');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Back','Seated Cable Row');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Back','Deadlift');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Back','Trap Bar Deadlift');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Back','Inverted Row');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Back','Chin-ups');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Back','Straight-arm Pulldown');

INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Shoulders','	Overhead Press');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Shoulders','	Arnold Press');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Shoulders','	Dumbbell Shoulder Press');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Shoulders','	Barbell Shoulder Press');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Shoulders','	Lateral Raise');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Shoulders','	Front Raise');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Shoulders','	Rear Delt Fly');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Shoulders','	Upright Row');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Shoulders','	Cable Lateral Raise');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Shoulders','	Face Pull');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Shoulders','	Push Press');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Shoulders','	Pike Push-Up');

INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Biceps','Barbell Curl');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Biceps','Dumbbell Curl');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Biceps','Hammer Curl');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Biceps','Preacher Curl');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Biceps','Concentration Curl');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Biceps','Cable Curl');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Biceps','Incline Dumbbell Curl');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Biceps','Zottman Curl');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Biceps','Chin-Up');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Biceps','EZ-Bar Curl');

INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Triceps','Triceps Pushdown');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Triceps','Overhead Triceps Extension');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Triceps','Skull Crushers');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Triceps','Close-Grip Bench Press');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Triceps','Dips');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Triceps','Kickbacks');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Triceps','Diamond Push-Ups');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Triceps','Rope Pushdown');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Triceps','Dumbbell Overhead Extension');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Triceps','Cable Overhead Triceps Extension');

INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Abs','Crunches');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Abs','Sit-Ups');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Abs','Plank');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Abs','Bicycle Crunches');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Abs','Leg Raises');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Abs','Russian Twists');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Abs','Mountain Climbers');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Abs','Flutter Kicks');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Abs','V-Ups');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Abs','Hanging Leg Raises');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Abs','Reverse Crunches');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Abs','Toe Touches');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Abs','Side Plank');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Abs','Dead Bug');


INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Glutes','Hip Thrusts');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Glutes','Glute Bridges');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Glutes','Donkey Kicks');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Glutes','Fire Hydrants');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Glutes','Step-Ups');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Glutes','Cable Kickbacks');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Glutes','Kettlebell Swings');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Glutes','Resistance Band Walks');


INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Calves','Standing Calf Raises');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Calves','Seated Calf Raises');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Calves','Donkey Calf Raises');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Calves','Single-Leg Calf Raises');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Calves','Calf Press on Leg Machine');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Calves','Jump Rope');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Calves','Farmer s Walk on Toes');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Calves','Box Jumps');

INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Forearms','Cable Wrist Curls');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Forearms','Reverse Cable Wrist Curls');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Forearms','Wrist Curls');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Forearms','Reverse Wrist Curls');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Forearms','Hammer Curls');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Forearms','Reverse Curls');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Forearms','Plate Pinches');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Forearms','Barbell Holds');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Forearms','Dead Hangs');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Forearms','Zottman Curls');

INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Traps','Barbell Shrugs');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Traps','Dumbbell Shrugs');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Traps','Upright Rows');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Traps','Face Pulls');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Traps','Cable Shrugs');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Traps','Overhead Barbell Carries');


INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Hamstrings','Romanian Deadlifts');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Hamstrings','Lying Leg Curls');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Hamstrings','Seated Leg Curls');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Hamstrings','Good Mornings');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Hamstrings','Kettlebell Swings');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Hamstrings','Glute-Ham Raises');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Hamstrings','Cable Leg Curls');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Hamstrings','Single-Leg Curl');

INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Quadriceps','Barbell Back Squat');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Quadriceps','Front Squat');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Quadriceps','Leg Press');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Quadriceps','Walking Lunges');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Quadriceps','Bulgarian Split Squat');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Quadriceps','Leg Extension');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Quadriceps','Sissy Squat');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Quadriceps','Sumo Squats');
INSERT INTO muscle(muscle_cible,nom_exercice) VALUES ('Quadriceps','Step-Ups');

 


