/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package beastlog;
import dao.ConnectionProvider;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.SpinnerDateModel;
import javax.swing.JSpinner;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.Exercise;

/**
 *
 * @author user1
 */
public class AddWorkout extends javax.swing.JFrame {
    private String currentUsername;


    /**
     * Creates new form AddWorkout
     */
    public AddWorkout(String username) {
        initComponents();
        
        this.currentUsername = username;
        
        comboMuscle.addItem("Chest");
        comboMuscle.addItem("Back");
        comboMuscle.addItem("Shoulders");
        comboMuscle.addItem("Biceps");
        comboMuscle.addItem("Triceps");
        comboMuscle.addItem("Abs");
        comboMuscle.addItem("Glutes");
        comboMuscle.addItem("Calves");
        comboMuscle.addItem("Forearms");
        comboMuscle.addItem("Traps");
        comboMuscle.addItem("Hamstrings");
        comboMuscle.addItem("Quadriceps");
        
        
        comboMuscle.addActionListener(e -> {
        String selectedMuscle = (String) comboMuscle.getSelectedItem();
        updateExercisesCombo(selectedMuscle);
        });
        
        // Initialisation du Spinner de date
        SpinnerDateModel dateModel = new SpinnerDateModel();
        date_sp.setModel(dateModel);
        date_sp.setEditor(new JSpinner.DateEditor(date_sp, "dd-MM-yyyy"));
        JSpinner.DefaultEditor editor = (JSpinner.DefaultEditor) date_sp.getEditor();
        editor.getTextField().setEditable(false);  // Bloque la saisie manuelle
        // Désactive les boutons via le UI
        UIManager.put("Spinner.disableOnBoundaryValues", true);
        date_sp.updateUI();
        // Rend les boutons inactifs mais visibles
        date_sp.getComponent(0).setEnabled(false);  // Flèche haute
        date_sp.getComponent(1).setEnabled(false);  // Flèche basse
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        date_sp = new javax.swing.JSpinner();
        comboMuscle = new javax.swing.JComboBox<>();
        comboExercise = new javax.swing.JComboBox<>();
        serie_sp = new javax.swing.JSpinner();
        rep_sp = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        addbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        poids_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("Date");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 60, -1));

        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("Targeted Muscle");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 180, -1));

        jLabel4.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("Exercise");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 100, -1));

        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("Series");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 70, -1));

        jLabel6.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText("Repetitions");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 120, -1));

        date_sp.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        getContentPane().add(date_sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 250, 40));

        comboMuscle.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        comboMuscle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMuscleActionPerformed(evt);
            }
        });
        getContentPane().add(comboMuscle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 250, 40));

        comboExercise.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        comboExercise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboExerciseActionPerformed(evt);
            }
        });
        getContentPane().add(comboExercise, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 250, 40));

        serie_sp.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        getContentPane().add(serie_sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 250, 40));

        rep_sp.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        getContentPane().add(rep_sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 250, 40));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Targeted Muscle", "Exercice", "Series", "Repetitions", "Weight"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 620, 440));

        addbtn.setBackground(new java.awt.Color(255, 102, 0));
        addbtn.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        addbtn.setForeground(new java.awt.Color(255, 255, 255));
        addbtn.setText(" Add ");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 620, 120, 50));

        backbtn.setBackground(new java.awt.Color(204, 102, 0));
        backbtn.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 700, 110, 50));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, -1, -1));

        jLabel8.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 51, 0));
        jLabel8.setText("Weight (kg)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, -1, -1));

        poids_txt.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        poids_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poids_txtActionPerformed(evt);
            }
        });
        getContentPane().add(poids_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 250, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add workout.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        
       
        try{
            Exercise ex = new Exercise();
            
            //Date depuis le JSpinner
            java.util.Date selectedDate = (java.util.Date) date_sp.getValue(); 
            ex.date_ex = selectedDate;
            
            //username
            ex.username_ex= currentUsername;
            
            //muscle et exercice depuis JComboBox
            ex.muscle_cible= comboMuscle.getSelectedItem().toString();
            ex.exercise= comboExercise.getSelectedItem().toString();
            
            //serie et repetition depuis JSpinner
            ex.serie = (Integer)serie_sp.getValue();
            ex.repetition = (Integer)rep_sp.getValue();
            
            //poids depuis JTextField
            ex.poids = Double.parseDouble(poids_txt.getText());
            
            
            if (ex.serie == 0) {
                JOptionPane.showMessageDialog(this, "Please type number of series");
                return;
            }
            
            if (ex.repetition == 0) {
                JOptionPane.showMessageDialog(this, "Please type number of repetitions");
                return;
            }
            
            ex.save();
            
            // Mise à jour du tableau (ajout dans le model)
            DefaultTableModel model = (DefaultTableModel) Table.getModel();
            model.addRow(new Object[] {
                ex.muscle_cible,
                ex.exercise,
                ex.serie,
                ex.repetition,
                ex.poids
            });
            
            //JOptionPane.showMessageDialog(this,"Exercise added successfully !");
        
        
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Erreur : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
    }//GEN-LAST:event_addbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new HomePage(currentUsername).setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    private void comboMuscleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMuscleActionPerformed
        // TODO add your handling code here:
        String selectedMuscle = (String) comboMuscle.getSelectedItem();
        updateExercisesCombo(selectedMuscle);
    }//GEN-LAST:event_comboMuscleActionPerformed

    private void comboExerciseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboExerciseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboExerciseActionPerformed

    private void poids_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poids_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poids_txtActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        
        
    }//GEN-LAST:event_TableMouseClicked

   
    private void updateExercisesCombo(String muscle) {
    try {
        Connection con = ConnectionProvider.orclConnection();
        if (con != null){
            String query = " SELECT nom_exercice FROM muscle WHERE muscle_cible = ? ";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, muscle.trim());
            ResultSet rs = ps.executeQuery();

            comboExercise.removeAllItems(); // Vider les anciens exercices

            while (rs.next()) {
                // Récupération par index de colonne
                String exercice = rs.getString(1); 
                comboExercise.addItem(exercice);
            }

            rs.close();
            ps.close();
            con.close();
        }else{
            JOptionPane.showMessageDialog(this, "Connexion DB failed.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erreur : " + e.getMessage());
    }
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddWorkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddWorkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddWorkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddWorkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddWorkout("username").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton addbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JComboBox<String> comboExercise;
    private javax.swing.JComboBox<String> comboMuscle;
    private javax.swing.JSpinner date_sp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField poids_txt;
    private javax.swing.JSpinner rep_sp;
    private javax.swing.JSpinner serie_sp;
    // End of variables declaration//GEN-END:variables
}
