/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package beastlog;

import dao.ConnectionProvider;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author user1
 */
public class Stats extends javax.swing.JFrame {
    private String currentUsername;

    /**
     * Creates new form Stats
     */
    public Stats(String username) {
        initComponents();
        this.currentUsername = username;
        
        comboMuscle.addItem("Chest");
        comboMuscle.addItem("Back");
        comboMuscle.addItem("Shoulders");
        comboMuscle.addItem("Biceps");
        comboMuscle.addItem("Triceps");
        comboMuscle.addItem("Abs");
        comboMuscle.addItem("Glutes");
        comboMuscle.addItem("Calves");
        comboMuscle.addItem("Forearms");
        comboMuscle.addItem("Traps");
        comboMuscle.addItem("Hamstrings");
        comboMuscle.addItem("Quadriceps");
        
        
        comboMuscle.addActionListener(e -> {
        String selectedMuscle = (String) comboMuscle.getSelectedItem();
        updateExercisesCombo(selectedMuscle);
        });
        
        pr_txt.setEnabled(false); 
        date_txt.setEnabled(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboMuscle = new javax.swing.JComboBox<>();
        comboExercise = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pr_txt = new javax.swing.JTextField();
        date_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setText("Select : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 110, -1));

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("Muscle ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("Exercise");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        comboMuscle.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        comboMuscle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMuscleActionPerformed(evt);
            }
        });
        getContentPane().add(comboMuscle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 200, 40));

        comboExercise.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        getContentPane().add(comboExercise, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 200, 40));

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Show PR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, -1, 50));

        jButton2.setBackground(new java.awt.Color(255, 51, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back Home Page");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, -1, 50));

        jButton3.setBackground(new java.awt.Color(255, 51, 0));
        jButton3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("More");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 690, 110, 50));

        jLabel4.setFont(new java.awt.Font("Footlight MT Light", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("Your PR is : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("achieved on :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, -1, -1));

        pr_txt.setBackground(new java.awt.Color(255, 204, 102));
        pr_txt.setFont(new java.awt.Font("Footlight MT Light", 0, 24)); // NOI18N
        pr_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(pr_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 310, 230, 50));

        date_txt.setBackground(new java.awt.Color(255, 204, 102));
        date_txt.setFont(new java.awt.Font("Footlight MT Light", 0, 24)); // NOI18N
        date_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(date_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 490, 230, 50));

        jLabel7.setFont(new java.awt.Font("Footlight MT Light", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Kg");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 320, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/prpage.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboMuscleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMuscleActionPerformed
        String selectedMuscle = (String) comboMuscle.getSelectedItem();
        updateExercisesCombo(selectedMuscle);
    }//GEN-LAST:event_comboMuscleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        new HomePage(currentUsername).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String vmuscle = comboMuscle.getSelectedItem().toString().trim();
        String vexercise = comboExercise.getSelectedItem().toString().trim();
        try{
            Connection con = ConnectionProvider.orclConnection();
            String query =" SELECT poids, date_ex FROM exercise WHERE username_ex = ? AND muscle_cible = ? AND exercise = ? AND poids = ( SELECT MAX(poids) FROM exercise WHERE username_ex = ? AND muscle_cible = ? AND exercise = ? )";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, currentUsername);
            ps.setString(2, vmuscle);
            ps.setString(3, vexercise);
            ps.setString(4, currentUsername);
            ps.setString(5, vmuscle);
            ps.setString(6, vexercise);
            
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()){
                Double p = rs.getDouble(1);
                pr_txt.setText(p.toString());
                
                Date d = rs.getDate(2);
                date_txt.setText(d.toString()); 
            }
            else{
                JOptionPane.showMessageDialog(this, "This exercise is not found in your workout history.");
                pr_txt.setText("");
                date_txt.setText(""); 
            }
            rs.close();
            ps.close();
            con.close();
        }catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erreur : " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
        new Stat0(currentUsername).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void updateExercisesCombo(String muscle) {
    try {
        Connection con = ConnectionProvider.orclConnection();
        String query = " SELECT nom_exercice FROM muscle WHERE muscle_cible = ? ";
        PreparedStatement ps = con.prepareStatement(query);
        ps.setString(1, muscle.trim());
        ResultSet rs = ps.executeQuery();

        comboExercise.removeAllItems(); // Vider les anciens exercices

        while (rs.next()) {
            // Récupération par index de colonne
            String exercice = rs.getString(1); 
            comboExercise.addItem(exercice);
        }

        rs.close();
        ps.close();
        con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erreur : " + e.getMessage());
    }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stats("username").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboExercise;
    private javax.swing.JComboBox<String> comboMuscle;
    private javax.swing.JTextField date_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField pr_txt;
    // End of variables declaration//GEN-END:variables
}
