/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;
import dao.ConnectionProvider;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;

/**
 *
 * @author user1
 */
public class Exercise {
    public int id;
    public Date date_ex;
    public String username_ex;
    public String muscle_cible;
    public String exercise;
    public int serie;
    public int repetition;
    public double poids;
    
    public Exercise(){
        this.id=0;
        this.date_ex= new Date();
        this.username_ex="";
        this.muscle_cible="";
        this.exercise="";
        this.serie=0;
        this.repetition=0;
        this.poids=0.0;
    }
    
    public Exercise(int id, Date date_ex, String username_ex, String muscle_cible, String exercise, int serie, int repetition, double poids){
        this.id=id;
        this.date_ex=date_ex;
        this.username_ex=username_ex;
        this.muscle_cible=muscle_cible;
        this.exercise=exercise;
        this.serie=serie;
        this.repetition=repetition;
        this.poids=poids;
    }
    
    public static void creerTable(){
        try{
            String ExerciseTable="CREATE TABLE exercise (id_ex NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date_ex DATE, username_ex VARCHAR2(50) , muscle_cible VARCHAR2(50), exercise VARCHAR2(50), serie NUMBER, repetition NUMBER, poids NUMBER(7,3), CONSTRAINT fk_username FOREIGN KEY (username_ex) REFERENCES utilisateur (username) )";
            ConnectionProvider.operations(ExerciseTable, "ExerciseTable created successfully");
    }
       catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void save(){
        
      
        try(Connection con = ConnectionProvider.orclConnection()){ 
            
            String query = "INSERT INTO exercise (date_ex, username_ex, muscle_cible, exercise, serie, repetition, poids) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = con.prepareStatement(query);
            
            ps.setDate(1, new java.sql.Date(date_ex.getTime())); 
            ps.setString(2, username_ex);
            ps.setString(3, muscle_cible);
            ps.setString(4, exercise);
            ps.setInt(5, serie);
            ps.setInt(6, repetition);
            ps.setDouble(7, poids);
            
            ps.executeUpdate();
            
            con.close();
            ps.close();
            
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
}
